P317 Example 8.1

In [1]:
import numpy as np

In [2]:
N = 3
K = 3
mu = np.array([0.8, 0.6, 0.4])
m = np.array([2, 3, 1])
alpha = np.array([1.0, 0.667, 0.2])
rho = alpha / mu

In [3]:
def fact(n):
    if n <= 1:
        return 1
    return n * fact(n-1)

In [4]:
def getBeta(n, k): #P289 式 7.62
    if m[n] == 1:
        return 1
    elif k <= m[n]:
        return fact(k)
    elif k >= m[n]:
        return fact(m[n]) * m[n]**(k-m[n])

In [5]:
def getF(n, k):#n:ノード番号は1引いた数字
    f = (alpha[n]/mu[n])**k
    f /= getBeta(n, k)
    return f

In [6]:
for n in range(N):
    for k in range(K+1): 
        print('n = {0}, k = {1}, F = {2}'.format(n, k, getF(n, k)))

n = 0, k = 0, F = 1.0
n = 0, k = 1, F = 1.25
n = 0, k = 2, F = 0.78125
n = 0, k = 3, F = 0.48828125
n = 1, k = 0, F = 1.0
n = 1, k = 1, F = 1.1116666666666668
n = 1, k = 2, F = 0.617901388888889
n = 1, k = 3, F = 0.22896679243827167
n = 2, k = 0, F = 1.0
n = 2, k = 1, F = 0.5
n = 2, k = 2, F = 0.25
n = 2, k = 3, F = 0.125


In [7]:
def calcConvolution(n, k, rho): #メモ化利用なし
    #rho = alpha / mu
    if k == 0: #Gj(0) = 1 (j = 1,...,N)
        g = 1
    elif n == 0:#G(0,k) = f0(k)
        g = np.power(rho[n], k)
    else : 
        g = calcConvolution(n-1, k,rho) + rho[n] * calcConvolution(n, k-1,rho)
    return g

In [8]:
g = calcConvolution(N-1, K, rho) #ノード番号は1小さくしている
print(g)
#窓口数を考慮できないので値が合わない

9.418018115740743


In [9]:
def getConvolution(n, k, rho): #QN&MC P314 式(8.4),(8.5),(8.6)利用
    if k == 0:
        g = 1
    elif n == 0:
        g = getF(n, k)
    else :
        g = 0
        for i in range(k + 1):
            g += getF(n, i) * getConvolution(n-1, k-i, rho)
    #print('n = {0}, k = {1}, G(n,k) = {2}'.format(n, k, g)) #QN&MC P314 Table8.1
    return g

In [28]:
g = getConvolution(N-1, K, rho) #ノード番号は1小さくしている
print(g)

4.467898389660494


In [11]:
def getMarginalProbabilities(n, k): #QN&MC P316 式(8.13)
    pi = rho[n]**k / getConvolution(N-1, K, rho) * (getConvolution(N-1, K-k, rho) - rho[n] * getConvolution(N-1, K-k-1, rho))
    return pi

In [12]:
for k in range(K+1): #n = Nのとき
    marginal = getMarginalProbabilities(N-1, k) #ノード番号は1小さくしている
    print('pi({0},{1}) = {2}'.format(n, k, marginal))

pi(2,0) = 0.5277905082487573
pi(2,1) = 0.31208573685066865
pi(2,2) = 0.13214639527904107
pi(2,3) = 0.02797735962153304


In [27]:
def getGi(n, k, rho): #QN&MC P316 式(8.11), (8.12)
    if k == 0: #式(8.12)
        gi = 1
    else:
        gi = getConvolution(N-1, k, rho)
        for i in range(1, k + 1):
            gi -= getF(n, i) * getGi(n, k-i, rho)
    return gi

In [26]:
for n in range(N-1): #QN&MC P319確認
    for k in range(K+1):
        gi = getGi(n, k, rho)
        print('G({0},{1}) = {2}'.format(n, k, gi))

G(0,0) = 1
G(0,1) = 1.6116666666666668
G(0,2) = 1.423734722222222
G(0,3) = 0.9408341535493832
G(1,0) = 1
G(1,1) = 1.75
G(1,2) = 1.6562499999999996
G(1,3) = 1.3164062500000002


In [46]:
def getMarginal(): #QN&MC P315 式(8.7)
    mpi = np.zeros((N, K+1)) #周辺分布
    l = np.zeros(N) #平均系内人数
    for n in range(N):#周辺分布計算
        for k in range(K+1):
            mpi[n,k] = getF(n, k) * getGi(n, K - k, rho) / g
    for n in range(N):
        for k in range(K+1):
            l[n] += k * mpi[n,k]
    return mpi, l

In [47]:
mpi, l = getMarginal()
print(mpi)
print(l)

[[0.21057644 0.39832338 0.28181361 0.10928656]
 [0.29463657 0.41209485 0.24202149 0.05124709]
 [0.52779051 0.31208574 0.1321464  0.02797736]]
[1.28981029 1.0498791  0.66031061]
