P317 Example 8.1

In [1]:
import numpy as np

In [2]:
N = 3
K = 3
mu = np.array([0.8, 0.6, 0.4])
m = np.array([2, 3, 1])
alpha = np.array([1.0, 0.667, 0.2])
rho = alpha / mu

In [3]:
def fact(n):
    if n <= 1:
        return 1
    return n * fact(n-1)

In [4]:
def getBeta(n, k): #P289 式 7.62
    if m[n] == 1:
        return 1
    elif k <= m[n]:
        return fact(k)
    elif k >= m[n]:
        return fact(m[n]) * m[n]**(k-m[n])

In [5]:
def getF(n, k):#n:ノード番号は1引いた数字
    f = (alpha[n]/mu[n])**k
    f /= getBeta(n, k)
    return f

In [6]:
for n in range(N):
    for k in range(K+1): 
        print('n = {0}, k = {1}, F = {2}'.format(n, k, getF(n, k)))

n = 0, k = 0, F = 1.0
n = 0, k = 1, F = 1.25
n = 0, k = 2, F = 0.78125
n = 0, k = 3, F = 0.48828125
n = 1, k = 0, F = 1.0
n = 1, k = 1, F = 1.1116666666666668
n = 1, k = 2, F = 0.617901388888889
n = 1, k = 3, F = 0.22896679243827167
n = 2, k = 0, F = 1.0
n = 2, k = 1, F = 0.5
n = 2, k = 2, F = 0.25
n = 2, k = 3, F = 0.125


In [7]:
def calcConvolution(n, k, rho): #メモ化利用なし
    #rho = alpha / mu
    if k == 0: #Gj(0) = 1 (j = 1,...,N)
        g = 1
    elif n == 0:#G(0,k) = f0(k)
        g = np.power(rho[n], k)
    else : 
        g = calcConvolution(n-1, k,rho) + rho[n] * calcConvolution(n, k-1,rho)
    return g

In [8]:
g = calcConvolution(N-1, K, rho) #ノード番号は1小さくしている
print(g)
#窓口数を考慮できないので値が合わない

9.418018115740743


In [9]:
def getConvolution(n, k, rho): #QN&MC P314 式(8.4),(8.5),(8.6)利用
    if k == 0:
        g = 1
    elif n == 0:
        g = getF(n, k)
    else :
        g = 0
        for i in range(k + 1):
            g += getF(n, i) * getConvolution(n-1, k-i, rho)
    #print('n = {0}, k = {1}, G(n,k) = {2}'.format(n, k, g)) #QN&MC P314 Table8.1
    return g

In [10]:
g = getConvolution(N-1, K, rho) #ノード番号は1小さくしている
print(g)

4.467898389660494


In [11]:
def getMarginalProbabilities(n, k): #QN&MC P316 式(8.13)
    pi = rho[n]**k / getConvolution(N-1, K, rho) * (getConvolution(N-1, K-k, rho) - rho[n] * getConvolution(N-1, K-k-1, rho))
    return pi

In [12]:
for k in range(K+1): #n = Nのとき
    marginal = getMarginalProbabilities(N-1, k) #ノード番号は1小さくしている
    print('pi({0},{1}) = {2}'.format(n, k, marginal))

pi(2,0) = 0.5277905082487573
pi(2,1) = 0.31208573685066865
pi(2,2) = 0.13214639527904107
pi(2,3) = 0.02797735962153304


In [13]:
def getGi(n, k, rho): #QN&MC P316 式(8.11), (8.12)
    if k == 0: #式(8.12)
        gi = 1
    else:
        gi = getConvolution(N-1, k, rho)
        for i in range(1, k + 1):
            gi -= getF(n, i) * getGi(n, k-i, rho)
    return gi

In [14]:
for n in range(N-1): #QN&MC P319確認
    for k in range(K+1):
        gi = getGi(n, k, rho)
        print('G({0},{1}) = {2}'.format(n, k, gi))

G(0,0) = 1
G(0,1) = 1.6116666666666668
G(0,2) = 1.423734722222222
G(0,3) = 0.9408341535493832
G(1,0) = 1
G(1,1) = 1.75
G(1,2) = 1.6562499999999996
G(1,3) = 1.3164062500000002


In [15]:
def getMarginal(): #QN&MC P315 式(8.7)
    mpi = np.zeros((N, K+1)) #周辺分布
    l = np.zeros(N) #平均系内人数
    for n in range(N):#周辺分布計算
        for k in range(K+1):
            mpi[n,k] = getF(n, k) * getGi(n, K - k, rho) / g
    for n in range(N):
        for k in range(K+1):
            l[n] += k * mpi[n,k]
    return mpi, l

In [16]:
mpi, l = getMarginal()
print(mpi)
print(l)

[[0.21057644 0.39832338 0.28181361 0.10928656]
 [0.29463657 0.41209485 0.24202149 0.05124709]
 [0.52779051 0.31208574 0.1321464  0.02797736]]
[1.28981029 1.0498791  0.66031061]


P323 Example 8.2

In [17]:
N = 4
R = 2
K1 = 1
K2 = 2
mu = np.array([[1/1, 1/2],[1/4, 1/5],[1/8, 1/10],[1/12, 1/16]])
alpha = np.array([[1, 1],[0.4, 0.4],[0.4, 0.3],[0.2, 0.3]])
#Node1:Type2プロセッサシェアリング（Processor Sharing: PS）, Node2:Type4後着順割込継続型（LCFS-PR), Node3:Type4後着順割込継続型（LCFS-PR), Node4:Type3無限サーバ（Infinite Server: IS）, その他Type1(FCFS) 

In [18]:
# P323 Table 8.2 Fi(Si)の計算, P303式(7.82)
#Siはノードiにおけるクラス別人数分布:(ノードiのクラス0の人数, ノードiのクラス1の人数)
#Siは(0,0),(1,0),(0,1),(1,1),(0,2),(1,2) K1=1,K2=2なので
def FS(n, alpha, mu, Si, type_number):#sは状態分布, type_number =1(FCFS),2(PS),3(IS),4(LCFS-PR)
    f = 1
    if type_number == 1:
        print('FCFS') #ここはまだ未実装
    else:
        for r in range(R):#type-3はこのループで終わり
            f *= 1 / fact(Si[r]) * (alpha[n,r] / mu[n,r])**Si[r]
        if type_number == 2 or type_number == 4:#type-2,4は累乗をかける    
            f *= fact(sum(Si))
    return f

In [19]:
type_number = [2, 4, 4, 3]
type_list = [2, 4, 4, 3]
for n in range(N):
    for k1 in range(K1+1): #kのリストを作成
        for k2 in range(K2+1):
            f = FS(n, alpha, mu, [k1, k2], type_number[n])
            print('F{0}([{1},{2}]) = {3}'.format(n, k1, k2, f))

F0([0,0]) = 1.0
F0([0,1]) = 2.0
F0([0,2]) = 4.0
F0([1,0]) = 1.0
F0([1,1]) = 4.0
F0([1,2]) = 12.0
F1([0,0]) = 1.0
F1([0,1]) = 2.0
F1([0,2]) = 4.0
F1([1,0]) = 1.6
F1([1,1]) = 6.4
F1([1,2]) = 19.200000000000003
F2([0,0]) = 1.0
F2([0,1]) = 2.9999999999999996
F2([0,2]) = 8.999999999999998
F2([1,0]) = 3.2
F2([1,1]) = 19.2
F2([1,2]) = 86.39999999999999
F3([0,0]) = 1.0
F3([0,1]) = 4.8
F3([0,2]) = 11.52
F3([1,0]) = 2.4000000000000004
F3([1,1]) = 11.520000000000001
F3([1,2]) = 27.648000000000003


In [20]:
def getConvolution(n, alpha, mu, Si, type_num):#P321式(8.21)
    g = 0
    type_list = [2, 4, 4, 3] #type_listに名前変更(type_numberはFSの時は番号が変わらないのでいいが、再帰の時は番号が変わるのでtype_listと変えた。FSもtype_listとして処理した方が混乱しなくていいかも)
    if n == 0:
        g = FS(n, alpha, mu, Si, type_num)#
    elif n >= 1:
        for i in range(Si[0]+1):#課題：今回は2クラスなので２重ループでよかった。多クラスの対応を考える
            for j in range(Si[1]+1):#解決法：重複組合せをリストで返す関数を呼び出し、そのリストをループで回せば良い
                g += getConvolution(n-1, alpha, mu, [i,j], type_list[n-1]) * FS(n, alpha, mu, [Si[0]-i, Si[1]-j], type_num) #ここも多クラスの時の課題
    return g            

In [21]:
GK = 0
for n in range(N): #P324 Table 8.3
    for k1 in range(K1+1):
        for k2 in range(K2+1):
            g = getConvolution(n, alpha, mu, [k1,k2], type_list[n])
            print('G{0}({1},{2}) = {3}'.format(n,k1,k2,g))
            if n == N-1 and k1 == K1 and k2 == K2: #定常分布で使うためGKを確保
                GK = g
print(GK)

G0(0,0) = 1.0
G0(0,1) = 2.0
G0(0,2) = 4.0
G0(1,0) = 1.0
G0(1,1) = 4.0
G0(1,2) = 12.0
G1(0,0) = 1.0
G1(0,1) = 4.0
G1(0,2) = 12.0
G1(1,0) = 2.6
G1(1,1) = 15.600000000000001
G1(1,2) = 62.4
G2(0,0) = 1.0
G2(0,1) = 7.0
G2(0,2) = 33.0
G2(1,0) = 5.800000000000001
G2(1,1) = 55.4
G2(1,2) = 334.2
G3(0,0) = 1.0
G3(0,1) = 11.8
G3(0,2) = 78.12
G3(1,0) = 8.200000000000001
G3(1,1) = 111.56
G3(1,2) = 854.424
854.424


In [22]:
def getGi(n, Si, alpha, mu): #P322 式(8.25,26,27) 引数nはG_N^(i)のiに対応する
    if sum(Si) == 0: #式(8.27)
        gi = 1
    else:
        gi = getConvolution(N-1, alpha, mu, Si, type_list[N-1])
        for k1 in range(Si[0]+1): #Siになるまでの全ての組み合わせ(課題：多クラスにも対応できるようにする)
            for k2 in range(Si[1]+1):
                if(k1 + k2 == 0):#j=0の場合は除く(8.26) 
                    continue
                else:
                    gi -= FS(n, alpha, mu, [k1, k2], type_list[n]) * getGi(n, [Si[0]-k1, Si[1]-k2], alpha, mu)
    return gi

In [23]:
for n in range(N):
    for k1 in range(K1+1):
        for k2 in range(K2+1):
            gi = getGi(n, [k1, k2], alpha, mu)
            print('GN({0})({1},{2}) = {3}'.format(n, k1, k2, gi))
#最終ノードを除いた場合GN(3)(0,0) = 1 ~は数値OKだが、他のノードを除いた場合は確認できない

GN(0)(0,0) = 1
GN(0)(0,1) = 9.8
GN(0)(0,2) = 54.52
GN(0)(1,0) = 7.200000000000001
GN(0)(1,1) = 83.36
GN(0)(1,2) = 553.184
GN(1)(0,0) = 1
GN(1)(0,1) = 9.8
GN(1)(0,2) = 54.52
GN(1)(1,0) = 6.600000000000001
GN(1)(1,1) = 76.27999999999999
GN(1)(1,2) = 506.31200000000007
GN(2)(0,0) = 1
GN(2)(0,1) = 8.8
GN(2)(0,2) = 42.720000000000006
GN(2)(1,0) = 5.000000000000001
GN(2)(1,1) = 49.2
GN(2)(1,2) = 269.7599999999999
GN(3)(0,0) = 1
GN(3)(0,1) = 7.000000000000001
GN(3)(0,2) = 33.0
GN(3)(1,0) = 5.800000000000001
GN(3)(1,1) = 55.399999999999984
GN(3)(1,2) = 334.20000000000005


In [30]:
#定常分布を求める
#G(K)をgetConvolutionでN=n-1、Si=[K1,K2]となった時がGKなので最初にそれを取得してから(8.23)を計算する
def getMarginalProbability(n, Si, alpha, mu):
    mp = FS(n, alpha, mu, Si, type_list[n]) * getGi(n, [K1-Si[0], K2-Si[1]], alpha, mu) / GK
    return mp

In [31]:
for n in range(N):
    for k1 in range(K1+1):
        for k2 in range(K2+1):
            mp = getMarginalProbability(n, [k1, k2], alpha, mu)
            print('mp({0})({1},{2}) = {3}'.format(n, k1, k2, mp))

mp(0)(0,0) = 0.647434997144275
mp(0)(0,1) = 0.19512560508599947
mp(0)(0,2) = 0.033706918344990316
mp(0)(1,0) = 0.06380906903364138
mp(0)(1,1) = 0.04587886108068126
mp(0)(1,2) = 0.01404454931041263
mp(1)(0,0) = 0.5925769875378033
mp(1)(0,1) = 0.17855303689971253
mp(1)(0,2) = 0.03089800848290779
mp(1)(1,0) = 0.10209451045382623
mp(1)(1,1) = 0.07340617772909001
mp(1)(1,2) = 0.02247127889666021
mp(2)(0,0) = 0.31572146849807575
mp(2)(0,1) = 0.17274795651807534
mp(2)(0,2) = 0.05266705991404736
mp(2)(1,0) = 0.15999550574422072
mp(2)(1,1) = 0.19774725429060983
mp(2)(1,2) = 0.10112075503497092
mp(3)(0,0) = 0.39114069829499176
mp(3)(0,1) = 0.31122721271874376
mp(3)(0,2) = 0.07820005056037753
mp(3)(1,0) = 0.09269402544872338
mp(3)(1,1) = 0.09437937136597288
mp(3)(1,2) = 0.0323586416111907
